name: GitHub Readme Chess

on:
  issues:
    types: [opened]

jobs:
  update-chess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Play Chess Game
        uses: zandens/github-readme-chess@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
